version: 2.1

jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - sample-springboot-api-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sample-springboot-api-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn test

      - run: mvn clean package