version: 2

jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
      - run:
          name: Package jar
          command: mvn package
