version: 2

jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-stretch

    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
